parameters:
    bigfoot_seo.metadatatype.class: 'Bigfoot\Bundle\SeoBundle\Form\MetadataType'
    bigfoot_seo.metadataparametertype.class: 'Bigfoot\Bundle\SeoBundle\Form\MetadataParameterType'

services:
    form.type.metadata:
        class: '%bigfoot_seo.metadatatype.class%'
        arguments: [@service_container]
        tags:
            - { name: form.type, alias: metadata }
    form.type.metadataparameter:
            class: '%bigfoot_seo.metadataparametertype.class%'
            arguments: [@service_container]
            tags:
                - { name: form.type, alias: metadataparameter }

    # bigfoot_seo.helper:
    #     class: Bigfoot\Bundle\SeoBundle\Helper\SeoHelper
    #     arguments: [ @service_container ]

    # Menu Listener
    bigfoot_seo.listener.menu:
        class: Bigfoot\Bundle\SeoBundle\Listener\MenuListener
        tags:
            - { name: kernel.event_subscriber }