parameters:
    bigfoot_seo.metadatatype.class: 'Bigfoot\Bundle\SeoBundle\Form\MetadataType'
    bigfoot_seo.metadataparametertype.class: 'Bigfoot\Bundle\SeoBundle\Form\MetadataParameterType'

services:
    form.type.metadata:
        class: '%bigfoot_seo.metadatatype.class%'
        arguments: [@bigfoot_seo.manager.route]
        tags:
            - { name: form.type, alias: metadata }
    form.type.metadataparameter:
            class: '%bigfoot_seo.metadataparametertype.class%'
            arguments: [@bigfoot_seo.manager.route]
            tags:
                - { name: form.type, alias: metadataparameter }

    bigfoot_seo.helper:
        class: Bigfoot\Bundle\SeoBundle\Helper\SeoHelper
        arguments: [ @service_container ]

    # Menu Subscriber
    bigfoot_seo.subscriber.menu:
        class: Bigfoot\Bundle\SeoBundle\Subscriber\MenuSubscriber
        arguments:
            - @security.context
        tags:
            - { name: kernel.event_subscriber }

     # Content Extension
    bigfoot_seo.twig.extension.seo:
        class: Bigfoot\Bundle\SeoBundle\Twig\Extension\SeoExtension
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: twig.extension }

     # Manager
    bigfoot_seo.manager.route:
        class: Bigfoot\Bundle\SeoBundle\Manager\RouteManager
        arguments:
            - @router
            - %bigfoot_seo%
